db_url: jdbc:mysql://profile-staging2.c2bryi0pfxhi.us-east-1.rds.amazonaws.com:3306/amee_profile
db_driver: com.mysql.jdbc.Driver
db_user: amee_profile
db_password: #edit me

output_file: score.csv

batch_size: 50000

iterate_sql: select amee_company_id from companies order by amee_company_id asc

export_sql: |
  select
  amee_company_id,
  uk_sic_2007,
  amee_industry_score,
  financial_intensity,
  emissions_total,
  annual_sales_local,
  amee_score_group

  from companies c
  where c.amee_company_id >= ?
  and c.amee_company_id <= ?

